// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using TodoApp.Models;

namespace TodoApp.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    partial class ApplicationDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("ProductVersion", "5.0.9")
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("TodoApp.Models.TodoModel", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsComplete")
                        .HasColumnType("bit");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("TodoModel");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Description = "suitable for men and women",
                            IsComplete = true,
                            Name = "Vanz"
                        },
                        new
                        {
                            Id = 2,
                            Description = "suitable for men and women",
                            IsComplete = false,
                            Name = "Convert"
                        },
                        new
                        {
                            Id = 3,
                            Description = "suitable for men and women",
                            IsComplete = false,
                            Name = "Nike"
                        },
                        new
                        {
                            Id = 4,
                            Description = "suitable for men and women",
                            IsComplete = true,
                            Name = "Biti"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
